# Generated by Django 5.2 on 2026-04-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('unread', '未読'), ('reading', '読書中'), ('read', '読了'), ('sold', '販売済み'), ('disposed', '廃棄'), ('lost', '紛失'), ('transferred', '譲渡'), ('other', 'その他')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['id'],
            },
        ),
    ]
